import type { Metadata } from "next";
import "./globals.scss";
import { ThemeProvider } from "@mui/material";
import { lightTheme } from "./themes/themes";

export const metadata: Metadata = {
  title: "Audiostore - Your Story Starts Here ",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Parkinsans:wght@300..800&display=swap" rel="stylesheet"/>
      </head>

      <body suppressHydrationWarning>
          <ThemeProvider theme={lightTheme}>
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
